import { chromium } from 'playwright';
const navegador = await chromium.launch({ channel: 'chrome' });
const pagina = await navegador.newPage({ viewport: { width: 420, height: 900 } });
const eventos = [];
pagina.on('console', (m) => { if (['error', 'warning'].includes(m.type())) eventos.push(`[console.${m.type()}] ${m.text().slice(0, 300)}`); });
pagina.on('pageerror', (e) => eventos.push(`[pageerror] ${e.message.slice(0, 300)}`));
pagina.on('response', (r) => { if (r.status() >= 400) eventos.push(`[http ${r.status()}] ${r.url().slice(0, 160)}`); });
pagina.on('requestfailed', (r) => eventos.push(`[falhou] ${r.url().slice(0, 160)} ${r.failure()?.errorText}`));
await pagina.goto((process.env.ALVO || 'https://alobuzinou.com') + '/login', { waitUntil: 'networkidle' });
await pagina.waitForTimeout(3000);
const usar = pagina.getByText(/^Usar email$/).first();
if (await usar.isVisible().catch(() => false)) await usar.click();
await pagina.getByLabel('Email', { exact: true }).fill('sonda.teste.inexistente@example.com');
await pagina.getByLabel('Senha', { exact: true }).fill('senhaErrada123');
await pagina.locator('form button[type=submit]').first().click();
await pagina.waitForTimeout(6000);
await pagina.screenshot({ path: 'resultados/prod-login.png', fullPage: true });
const texto = await pagina.evaluate(() => document.body.innerText.replace(/\n+/g, ' | ').slice(0, 800));
console.log('TELA:', texto);
console.log(eventos.join('\n') || '(sem erros)');
await navegador.close();
